[Server]
# Server connection details
host =
port =
user =
password =
namespace =

[Project]
# Specify items belonging to the project here. Asterisks are
# supported. Examples:
# - All classes in package Strix:
#   Strix.*.cls
# - All include files:
#   *.inc
# Exclude rules are prefixed with a minus; assuming the above
# rules, the following then excludes all classes in package Strix.Work:
#   -Strix.Work.*.cls
# - All files in CSP application /csp/dev:
#   /csp/dev/*
# - ...except JPEG images:
#   -/csp/dev/*.jpg

[Local]
# Directory to place files in
dir =
# Whether to make directories for packages (1) or not (0)
# If true a.b.c.cls will become a\b\c.cls.
subdirs = 1
# directory for CSP files, if any
cspdir =


