[Server]
# Server connection details
host =
port =
user =
password =
namespace =

[Project]
# Specify items belonging to the project here. Asterisks are
# supported. Examples:
# - All classes in package Strix:
#   Strix.*.cls
# - All include files:
#   *.inc
# Exclude rules are prefixed with a minus; assuming the above
# rules, the following then excludes all classes in package Strix.Work:
#   -Strix.Work.*.cls
# - All files in CSP application /csp/dev:
#   /csp/dev/*
# - ...except JPEG images:
#   -/csp/dev/*.jpg

[Local]
# Directory to place files in
dir =

# Encoding for (non-binary) files; use valid Python
# encoding string, e.g. UTF-8 or CP1252.
encoding =

# Whether to make directories for packages (1) or not (0)
# If true a.b.c.cls will become a\b\c.cls.
subdirs = 1

# directory for CSP files, if any. This should normally be
# kept outside the non-CSP items directory, so that one can
# be used with $System.OBJ.ImportDir().
cspdir =

# Whether to save a file (per connection) with cookies, so that
# the CSP licence can be retained between runs. This is only needed
# if many successive runs are expected, and the CSP license allocation
# time is large.
cookies = 1

