#####
# Configuration file for copy-iris-items
# Syntax is TOML (https://toml.io/en/).

##### Server connection details: the server to retrieve the items from.
[Server]
host = ""
port = ""
namespace = ""
user = ""
password = ""
# Whether HTTPS is needed to connect to IRIS.
https = false
# The number of threads (paralell fetches) to use. Must be a number
# between 1 (not parallel) and 20 (the maximum number of concurrent
# fetches).
threads = 1


##### What belongs to this project
[Project]
# Specify items belonging to the project here. Wildcards using asterisks
# are supported. Exclude rules are prefixed with a minus. CSP files are
# supported; specify them starting with their URL path (e.g.
# '/csp/dev/*').
items = [
]

# Whether to include items mapped from another database.
mapped = false

# Whether to include generated items.
generated = false

# Ensemble Data Lookup Tables to include.
lookup = [
]

[Project.enssettings]
# Ensemble/interoperability: system default settings. Leave the name empty
# to prevent retrieving them. The name used in Ensemble deployments is
# "Ens.Config.DefaultSettings.esd".
name = ""
# Whether to strip values from the settings.
strip = true


##### Where and how to save things.
[Local]
# Directories which are not an absolut path, will be taken relative to
# the location of the configuration file. The string {cfgname} will be
# replaced by the name of the configuration file

# Directory to place source files (class, mac, inc, etc.) in.
dir = '{cfgname}\src'

# Directory for CSP files.
cspdir = '{cfgname}\csp'

# Directory for data files.
datadir = '{cfgname}\data'

# Directory for the log file. If empty, the log file is placed adjacent
# to the configuration file.
logdir = ""

# Encoding for (non-binary) files; default is UTF-8.
encoding = "UTF-8"

# Whether to make directories for packages (true) or not (false)
subdirs = true

# Whether to save a file (per connection) with cookies, so that the CSP
# licence can be retained between runs.
cookies = false

# Disable fix that makes sure the last newline of the file is present.
# Only use this for backward compatibility.
disable_eol_fix = false
