[Server]
# Server connection details: the server to retrieve the items from.
host =
port =
namespace =
user =
password =


[Project]
# Specify items belonging to the project here. Asterisks are
# supported. Examples:
# - All classes in package Strix:
#   Strix.*.cls
# - All include files:
#   *.inc
# CSP files are supported as well, and will be placed in the csp
# directory specified below.
# - All files in CSP application /csp/dev:
#   /csp/dev/*
# - Only CSP files, images, and css, nothing else:
#   /app/*.csp
#   /app/*.css
#   /app/*.js
# Exclude rules are prefixed with a minus; assuming the above
# rules, the following then excludes all classes in package Strix.Work,
# and temporary images:
#   -Strix.Work.*.cls
#   -/csp/dev/tmp*.jpg


[Data]
# Specify data items to save here.

# If Ensemble System Default Settings must be saved, specify the filename.
# Will be saved in the data directory.
enssettings = 
# Data lookup tables can be specified as a comma-separated list; no need
# to specify the '.lut' extension. Will be saved in the data directory.
lookup = 


[Local]
# Directory to place files in. Occurances of the string {ininame} will
# be replaced by the name of the ini file. Default is {ininame}\src.
dir = 

# Directory for CSP files, if any. This should normally be kept outside
# the non-CSP items directory, so that one can be used with
# $System.OBJ.ImportDir(). Occurances of the string {ininame} will
# be replaced by the name of the ini file. Default is {ininame}\csp.
cspdir = 

# Directory for data files, if any. Datafiles are e.g. data lookup table
# exports. Occurances of the string {ininame} will be replaced by the
# name of the ini file. Default is {ininame}\data.
datadir = 

# Encoding for (non-binary) files; use valid Python encoding
# string, e.g. UTF-8 or CP1252. Default is UTF-8.
encoding = 

# Whether to make directories for packages (1) or not (0)
# If true a.b.c.cls will become a\b\c.cls. Default = 1 (yes).
subdirs = 

# Whether to save a file (per connection) with cookies, so that
# the CSP licence can be retained between runs. This is only needed
# if many successive runs are expected, and the CSP license allocation
# time is large. Default = 0 (no).
cookies = 

